apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openelb-resource-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: openelb-resource-access
  apiGroup: rbac.authorization.k8s.io
	