apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openelb-resource-access
rules:
  - apiGroups: [ "network.kubesphere.io" ]
    resources: [ "bgpconfs", "bgppeers", "eips" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]